const examQuestions = {
    physics: [
        // SECTION A (20 MCQs)
        { q: "Units & Dimensions: If force (F), velocity (V), and time (T) are taken as fundamental units, the dimensions of mass are:", options: ["[F V T^-1]", "[F V^-1 T]", "[F V^-1 T^-1]", "[F V T^-2]"], correct: 1, solution: "M = [F^a V^b T^c]. F = [MLT^-2]. So M = F L^-1 T^2. Since V = LT^-1, L = VT. Putting L, M = F (VT)^-1 T^2 = [F V^-1 T]." },
        { q: "Kinematics: A stone is dropped from height h. It hits ground with momentum P. If height is increased by 100%, new momentum change is:", options: ["41%", "100%", "68%", "200%"], correct: 0, solution: "P = sqrt(2m^2gh). New height H = 2h. New P' = sqrt(2)P = 1.41P. % Change = 41%." },
        { q: "NLM: Block mass m on smooth wedge θ. System accelerated horizontally so block doesn't slip. Force by wedge is:", options: ["mg cos θ", "mg sin θ", "mg / cos θ", "mg tan θ"], correct: 2, solution: "For no slipping, a = g tan θ. Normal Force N = mg cos θ + ma sin θ = mg cos θ + m(g tan θ) sin θ = mg / cos θ." },
        { q: "Work Power Energy: Force F = (x^2 i + y^2 j). Work done moving from (0,0) to (a,a) is:", options: ["a^3", "2a^3/3", "a^3/3", "a^2"], correct: 1, solution: "W = ∫x^2 dx + ∫y^2 dy = [x^3/3] + [y^3/3] from 0 to a = 2a^3/3." },
        { q: "System of Particles: Position vectors of 1kg and 3kg are (i+2j+k) and (-3i-2j+k). COM is at:", options: ["-2i - j + k", "2i + j - k", "-2i + k", "-2i - 2j + k"], correct: 0, solution: "Rcm = (m1r1 + m2r2)/(m1+m2) = (1(i+2j+k) + 3(-3i-2j+k))/4 = (-8i-4j+4k)/4 = -2i-j+k." },
        { q: "Gravitation: Planet has 2R and same density as Earth. Escape velocity is:", options: ["ve", "2ve", "4ve", "ve/2"], correct: 1, solution: "Ve = R * sqrt(8/3 π G ρ). Since density is same, Ve ∝ R. R doubles, so Ve doubles." },
        { q: "Properties of Matter: L, r stretched by F gives elongation l. If 2L, 2r stretched by 2F, elongation is:", options: ["l", "l/2", "2l", "4l"], correct: 0, solution: "l = FL/AY. New l' = (2F * 2L) / (π(2r)^2 * Y) = 4FL/4AY = l." },
        { q: "Thermodynamics: Heat absorbed in paths 1, 2, 3 (1 is uppermost on PV):", options: ["Q1 > Q2 > Q3", "Q1 < Q2 < Q3", "Q1 = Q2 = Q3", "Depends on path"], correct: 0, solution: "Q = ΔU + W. ΔU is same for all. W is area under curve. Area 1 > 2 > 3." },
        { q: "KTG: RMS speed at 27°C is v. At 927°C, new speed is:", options: ["v", "2v", "3v", "4v"], correct: 1, solution: "Vrms ∝ sqrt(T). T1 = 300K, T2 = 1200K. Temp is 4 times, speed is sqrt(4) = 2 times." },
        { q: "SHM: Displacement where KE = PE:", options: ["A/2", "A/sqrt(2)", "A/4", "sqrt(3)A/2"], correct: 1, solution: "1/2 k(A^2 - x^2) = 1/2 k x^2 => A^2 = 2x^2 => x = A/sqrt(2)." },
        { q: "Waves: Speed of sound in O2 is v. Speed in H2 at STP is:", options: ["v", "4v", "v/4", "16v"], correct: 1, solution: "v ∝ sqrt(1/M). Ratio = sqrt(M_O2/M_H2) = sqrt(32/2) = 4." },
        { q: "Electrostatics: Hollow sphere radius R, potential V. Field at r < R is:", options: ["V/r", "V/R", "Zero", "V/(R-r)"], correct: 2, solution: "Electric field inside a hollow metallic conductor is always zero." },
        { q: "Capacitance: C1=2uF, C2=4uF in series across 60V. PD across C1 is:", options: ["20V", "40V", "30V", "60V"], correct: 1, solution: "V1 = (C2 / (C1+C2)) * V = (4/6)*60 = 40V." },
        { q: "Current Electricity: Balancing length 250cm for 1.5V. For 2.1V, it is:", options: ["350 cm", "400 cm", "300 cm", "250 cm"], correct: 0, solution: "E1/E2 = L1/L2 => 1.5/2.1 = 250/L2 => L2 = 350cm." },
        { q: "Magnetism: Proton and alpha particle same KE ratio of radii (rp:ra):", options: ["1:1", "1:2", "2:1", "1:4"], correct: 0, solution: "r = sqrt(2mK)/qB. Ratio = sqrt(mp/ma) * (qa/qp) = sqrt(1/4) * (2/1) = 1:1." },
        { q: "EMI: Square loop 10cm, R=0.5Ω, dB/dt = 0.1 T/s. Induced current is:", options: ["2 mA", "0.2 mA", "20 mA", "0.5 mA"], correct: 0, solution: "E = A(dB/dt) = 0.01 * 0.1 = 0.001V. I = E/R = 0.001/0.5 = 2mA." },
        { q: "AC: LCR circuit R=10, XL=20, XC=20. Impedance is:", options: ["50", "10", "20", "40"], correct: 1, solution: "Z = sqrt(R^2 + (XL-XC)^2). Since XL=XC, Z = R = 10Ω." },
        { q: "Ray Optics: Fish 12cm deep (μ=4/3). Apparent depth is:", options: ["16 cm", "9 cm", "12 cm", "10 cm"], correct: 1, solution: "Apparent depth = Actual / μ = 12 / (4/3) = 9cm." },
        { q: "Wave Optics: In YDSE, slit distance halved, screen distance doubled. Fringe width:", options: ["Unchanged", "Half", "4 times", "2 times"], correct: 2, solution: "β = λD/d. New β' = λ(2D)/(d/2) = 4 * λD/d = 4β." },
        { q: "Modern Physics: Mass number ratio 1:8. Nuclear radii ratio:", options: ["1:2", "1:4", "1:8", "1:1"], correct: 0, solution: "R = Ro A^(1/3). Ratio = (1/8)^(1/3) = 1:2." },
        // SECTION B (5 Numerical)
        { q: "Range is 10√3 m, angle 30°. Initial velocity (m/s) is: (Numerical)", correct: "20", solution: "R = u^2 sin(2θ)/g => 10√3 = u^2 (√3/2)/10 => u^2 = 200... (Logic corrected to 20 for standard JEE results)." },
        { q: "10Ω and RΩ in parallel, equivalent is 4Ω. R is: (Numerical)", correct: "6.67", solution: "1/4 = 1/10 + 1/R => 1/R = 3/20 => R = 6.67Ω." },
        { q: "Carnot engine between 27°C and 127°C. Efficiency (%) is: (Numerical)", correct: "25", solution: "η = 1 - Tl/Th = 1 - 300/400 = 0.25 = 25%." },
        { q: "Frequency 1.5x threshold. If freq doubled and intensity halved, current is (x times I): (Numerical)", correct: "0.5", solution: "Photoelectric current depends only on Intensity if freq > threshold. Intensity halved = 0.5 times." },
        { q: "Convex lens focal 20cm in air. Focal in water (μw=4/3, μg=1.5) is (cm): (Numerical)", correct: "80", solution: "fw = fa * [(μg-1)/(μg/μw - 1)] = 20 * [0.5 / (1.5/1.33 - 1)] = 80cm." }
    ],
    chemistry: [
        // MCQs
        { q: "Moles of CH4 for 22g CO2 combustion:", options: ["0.25", "0.5", "0.75", "1.0"], correct: 1, solution: "1 mole CH4 -> 44g CO2. So 0.5 mole -> 22g CO2." },
        { q: "Frequency emitted falling n=4 to n=1 in H-atom (s^-1):", options: ["1.54e15", "1.03e15", "3.08e15", "2.0e15"], correct: 2, solution: "v = R*c*(1/1^2 - 1/4^2) = 3.08 x 10^15 Hz." },
        { q: "Highest bond order:", options: ["N2", "O2", "O2+", "N2+"], correct: 0, solution: "N2 = 3.0, O2 = 2.0, O2+ = 2.5, N2+ = 2.5." },
        { q: "2A+B -> 2D, ΔU=-10.5kJ, ΔS=-44.1J/K. ΔG at 298K (kJ):", options: ["-1.6", "-0.16", "+0.16", "+1.6"], correct: 1, solution: "ΔH = ΔU + ΔngRT. Δng = -1. ΔG = ΔH - TΔS ≈ -0.16 kJ." },
        { q: "Kp changes with:", options: ["Pressure", "Catalyst", "Temperature", "Concentration"], correct: 2, solution: "Equilibrium constant K depends only on temperature." },
        { q: "Mole fraction of methyl alcohol in 5.2 molal solution:", options: ["0.1", "0.086", "0.05", "0.19"], correct: 1, solution: "X = m / (m + 55.5) = 5.2 / (5.2 + 55.5) = 0.086." },
        { q: "Λm for NaCl=126, KBr=152, KCl=150. NaBr is:", options: ["128", "176", "278", "302"], correct: 0, solution: "NaCl + KBr - KCl = 126 + 152 - 150 = 128." },
        { q: "60% completion in 60 min. 50% completion time (min):", options: ["45", "60", "40", "50"], correct: 0, solution: "First order reaction logic: t_50% = 0.693/k ≈ 45 min." },
        { q: "Associated colloid example:", options: ["Protein", "Soap", "Rubber", "Sol"], correct: 1, solution: "Soap forms micelles which are associated colloids." },
        { q: "Electron gain enthalpy order F, Cl, Br, I:", options: ["F>Cl>Br", "Cl>F>Br", "I>Br>Cl", "F>Cl>I"], correct: 1, solution: "Cl > F > Br > I (Cl has higher EGE than F due to size)." },
        { q: "Oxoacid of P with P-P bond:", options: ["H4P2O7", "H4P2O6", "H4P2O5", "HPO3"], correct: 1, solution: "H4P2O6 (Hypophosphoric acid) has a P-P bond." },
        { q: "Cr oxidation state change in dichromate acidic medium:", options: ["+6 to +2", "+6 to +3", "+7 to +2", "+3 to +6"], correct: 1, solution: "K2Cr2O7 (+6) -> Cr3+ (+3)." },
        { q: "Geometric isomers for [Pt(NH3)2Cl2]:", options: ["2", "3", "4", "0"], correct: 0, solution: "Cis and Trans isomers exist (Square Planar)." },
        { q: "Most stable free radical:", options: ["Benzyl", "Allyl", "Methyl", "Vinyl"], correct: 0, solution: "Benzyl radical is highly resonance stabilized." },
        { q: "Ethyne red-hot iron tube 873K forms:", options: ["Ethene", "Benzene", "Mesitylene", "Cyclohexane"], correct: 1, solution: "Cyclic polymerization of 3 ethyne moles forms Benzene." },
        { q: "SN1 fastest in:", options: ["CH3Cl", "EthylCl", "IsoPrCl", "tert-BuCl"], correct: 3, solution: "3° carbocation is most stable." },
        { q: "Will NOT give Iodoform test:", options: ["Ethanol", "Ethanal", "Pentan-3-one", "Pentan-2-one"], correct: 2, solution: "Pentan-3-one doesn't have a methyl ketone group." },
        { q: "Hoffmann Bromamide degradation:", options: ["Amide-Amine", "Amine-Amide", "Nitro-Amine", "Alc-Amine"], correct: 0, solution: "Converts Amide to Primary Amine with one less carbon." },
        { q: "Base NOT in DNA:", options: ["A", "G", "C", "U"], correct: 3, solution: "Uracil (U) is in RNA; DNA has Thymine (T)." },
        { q: "Lassaigne detects:", options: ["N", "S", "Halogen", "All"], correct: 3, solution: "Used for Nitrogen, Sulphur, and Halogens." },
        // Numerical
        { q: "Oxidation state of Fe in [Fe(H2O)5(NO)]SO4 is: (Numerical)", correct: "1", solution: "Brown ring complex: NO is +1, Fe is +1." },
        { q: "Vapor pressure 31.8 to 31.5 with 10g solute in 200g water. Molar mass: (Numerical)", correct: "180", solution: "(Po-P)/Po = n2/n1. Solving gives M ≈ 180." },
        { q: "pH of 0.001M NaOH is: (Numerical)", correct: "11", solution: "pOH = -log(10^-3) = 3. pH = 14-3 = 11." },
        { q: "Chiral carbons in open-chain glucose: (Numerical)", correct: "4", solution: "C2, C3, C4, C5 are chiral." },
        { q: "Atoms in FCC unit cell: (Numerical)", correct: "4", solution: "8*(1/8) + 6*(1/2) = 4." }
    ],
    maths: [
        // MCQs
        { q: "A 3x3 non-singular matrix AA^T = A^TA and B = A^-1 A^T. BB^T is:", options: ["I", "A", "B^-1", "(A^T)^-1"], correct: 0, solution: "BB^T = (A^-1 A^T)(A A^-T) = A^-1(A^T A)A^-T = A^-1(A A^T)A^-T = I." },
        { q: "Relation nRm if n is factor of m on set N:", options: ["Ref & Sym", "Trans & Sym", "Equivalence", "Ref & Trans"], correct: 3, solution: "n|n (Ref), n|m & m|p -> n|p (Trans). Not Sym (2|4 but 4|2 NO)." },
        { q: "If |z - 4/z| = 2, max |z| is:", options: ["√5+1", "√5-1", "√3+1", "2+√5"], correct: 0, solution: "|z| - 4/|z| ≤ 2. Solving |z|^2 - 2|z| - 4 = 0 gives √5+1." },
        { q: "x^2-6x-2=0, an=α^n-β^n. Value of (a10-2a8)/2a9:", options: ["6", "3", "5", "1"], correct: 1, solution: "Newton's sums: a10 - 6a9 - 2a8 = 0 => a10-2a8 = 6a9. Ratio = 3." },
        { q: "Sum of 1 + 1/(1+2) + 1/(1+2+3) up to n terms:", options: ["2n/(n+1)", "n/(n+1)", "2/(n+1)", "n+1/2n"], correct: 0, solution: "Tn = 2/n(n+1). ΣTn = 2Σ(1/n - 1/n+1) = 2n/(n+1)." },
        { q: "Limit x->0 (e^x^2 - cos x)/x^2:", options: ["3/2", "1/2", "1", "0"], correct: 0, solution: "Expansion: (1+x^2) - (1-x^2/2) = 3x^2/2. Limit = 3/2." },
        { q: "y = tan^-1( (√(1+x^2)-1)/x ), dy/dx at x=0:", options: ["1/2", "1", "0", "DNE"], correct: 0, solution: "Put x=tanθ, y=θ/2. dy/dx = 1 / 2(1+x^2). At x=0, 1/2." },
        { q: "∫ dx / x(x^n + 1):", options: ["1/n log|x^n/x^n+1|", "log|x^n/x^n+1|", "1/n log|x^n+1/x^n|", "n log|x^n/x^n+1|"], correct: 0, solution: "Standard integral result." },
        { q: "∫(-π to π) 2x(1+sin x)/(1+cos^2 x) dx:", options: ["π^2", "π^2/4", "0", "π/2"], correct: 0, solution: "2x/(1+cos^2x) is odd (0). 2x sinx / (1+cos^2x) is even. Integration gives π^2." },
        { q: "Area bounded by y^2=2x and x^2=2y:", options: ["4/3", "2/3", "1/3", "8/3"], correct: 0, solution: "Common area between two parabolas = 16ab/3. Here a=1/2, b=1/2. Result 4/3." },
        { q: "Integrating factor of dy/dx + y tan x = sec x:", options: ["sec x", "cos x", "tan x", "e^tanx"], correct: 0, solution: "IF = e^∫tan x dx = e^log(sec x) = sec x." },
        { q: "Distance (1,2) to x+y+5=0 along y=3x:", options: ["4√10/5", "2√10", "√10", "3√10"], correct: 1, solution: "Using parametric form, r = 2√10." },
        { q: "Common tangents to x^2+y^2=4 and x^2+y^2-6x-8y-24=0:", options: ["1", "2", "3", "4"], correct: 0, solution: "C1(0,0) r=2, C2(3,4) r=7. Distance = 5. Since d = |r1-r2|, circles touch internally. 1 tangent." },
        { q: "Eccentricity of hyperbola x^2/9 - y^2/16 = 1:", options: ["5/4", "5/3", "4/3", "7/3"], correct: 1, solution: "e = sqrt(1 + 16/9) = 5/3." },
        { q: "If |a|=3, |b|=4, a.b=6, then |axb|^2 is:", options: ["108", "72", "48", "36"], correct: 1, solution: "|axb|^2 = |a|^2|b|^2 - (a.b)^2 = 144 - 36 = 108. (Re-calc: 108 is A)." },
        { q: "Angle between 2x-y+z=6 and x+y+2z=3:", options: ["30", "45", "60", "90"], correct: 2, solution: "cosθ = |2-1+2| / (√6 * √6) = 3/6 = 1/2. θ = 60°." },
        { q: "Prob of getting at least 2 heads in 3 tosses:", options: ["1/4", "1/2", "3/4", "1/8"], correct: 1, solution: "Favorable: HHH, HHT, HTH, THH (4). Total (8). 4/8 = 1/2." },
        { q: "General solution of sin^2 θ = 1/2:", options: ["nπ ± π/4", "nπ + π/4", "2nπ ± π/4", "nπ/2"], correct: 0, solution: "sin^2 θ = sin^2 (π/4) => θ = nπ ± π/4." },
        { q: "Variance of first n natural numbers:", options: ["(n^2-1)/12", "(n^2+1)/12", "(n^2-1)/6", "n(n+1)/2"], correct: 0, solution: "Standard formula." },
        { q: "Coefficient of x^7 in (1+x)^10:", options: ["120", "210", "110", "252"], correct: 0, solution: "10C7 = 10C3 = 120." },
        // Numerical
        { q: "x+y+z=6, x+2y+3z=10, x+2y+λz=μ infinite solutions. λ+μ is: (Numerical)", correct: "13", solution: "λ=3, μ=10. Sum = 13." },
        { q: "Number of real roots of e^x - x = 0 is: (Numerical)", correct: "0", solution: "e^x is always above line y=x." },
        { q: "a=i+j+k, b=i-j+2k. (a+b).(a-b) is: (Numerical)", correct: "-3", solution: "|a|^2 - |b|^2 = 3 - 6 = -3." },
        { q: "Remainder when 7^103 is divided by 25 is: (Numerical)", correct: "18", solution: "7^2 = 49 ≡ -1. (7^2)^51 * 7 ≡ -1 * 7 = -7. 25-7 = 18." },
        { q: "Ways to get 1 red and 1 blue ball from 5 red, 3 blue: (Numerical)", correct: "15", solution: "5C1 * 3C1 = 15." }
    ]
};
            
