const examQuestions = {
    physics: [
        // MCQs (Section A)
        { q: "Units & Dimensions: If force (F), velocity (V), and time (T) are fundamental units, dimensions of mass are:", options: ["[F V T^-1]", "[F V^-1 T]", "[F V^-1 T^-1]", "[F V T^-2]"], correct: 1, solution: "M = [F^a V^b T^c]. Solving: M^1 = [M^1 L^1 T^-2]^a [L^1 T^-1]^b [T^1]^c. a=1, b=-1, c=1. Ans: (B)" },
        { q: "Kinematics: Stone dropped from height h has momentum P. If dropped from height 100% more (2h), momentum changes by:", options: ["41%", "100%", "68%", "200%"], correct: 0, solution: "P = sqrt(2m^2gh). If h -> 2h, P' = sqrt(2)P. Change = (sqrt(2)-1)*100 ≈ 41.4%. Ans: (A)" },
        { q: "NLM: Block on smooth wedge (θ). System accelerated horizontally so block doesn't slip. Force by wedge on block:", options: ["mg cos θ", "mg sin θ", "mg / cos θ", "mg tan θ"], correct: 2, solution: "For no slip, a = g tan θ. N = mg cos θ + ma sin θ = mg/cos θ. Ans: (C)" },
        { q: "WPE: Particle moves (0,0) to (a,a) under F = (x^2 i + y^2 j). Work done:", options: ["a^3", "2a^3/3", "a^3/3", "a^2"], correct: 1, solution: "W = ∫x^2 dx + ∫y^2 dy = [x^3/3] + [y^3/3] = 2a^3/3. Ans: (B)" },
        { q: "System of Particles: Masses 1kg and 3kg at (i+2j+k) and (-3i-2j+k). CM position:", options: ["-2i-j+k", "2i+j-k", "-2i+k", "-2i-2j+k"], correct: 0, solution: "Rcm = (m1r1 + m2r2)/(m1+m2) = (-8i-4j+4k)/4 = -2i-j+k. Ans: (A)" },
        { q: "Gravitation: Escape velocity is ve. Planet has twice radius and same density. New ve:", options: ["ve", "2ve", "4ve", "ve/2"], correct: 1, solution: "ve ∝ R * sqrt(rho). Since rho is same, ve ∝ R. If R doubles, ve doubles. Ans: (B)" },
        { q: "Matter: Wire (L, r) stretched by F elongation l. Wire (2L, 2r) stretched by 2F elongation:", options: ["l", "l/2", "2l", "4l"], correct: 0, solution: "l = FL/AY. New l' = (2F*2L)/(pi*4r^2*Y) = l. Ans: (A)" },
        { q: "Thermodynamics: Heat absorbed Q1, Q2, Q3 via 3 paths (Path 1 is uppermost):", options: ["Q1 > Q2 > Q3", "Q1 < Q2 < Q3", "Q1 = Q2 = Q3", "Depends on path"], correct: 0, solution: "ΔQ = ΔU + W. ΔU same. Area under path 1 is max, so Q1 is max. Ans: (A)" },
        { q: "KTG: RMS speed at 27°C is v. At 927°C, new speed is:", options: ["v", "2v", "3v", "4v"], correct: 1, solution: "v ∝ sqrt(T in K). T1=300K, T2=1200K. T becomes 4x, v becomes 2x. Ans: (B)" },
        { q: "SHM: Displacement from mean where KE = PE:", options: ["A/2", "A/sqrt(2)", "A/4", "sqrt(3)A/2"], correct: 1, solution: "1/2kx^2 = 1/2k(A^2-x^2) => 2x^2 = A^2 => x = A/sqrt(2). Ans: (B)" },
        { q: "Waves: Speed of sound in O2 at STP is v. Speed in H2 at STP:", options: ["v", "4v", "v/4", "16v"], correct: 1, solution: "v = sqrt(gamma*RT/M). v ∝ 1/sqrt(M). Ratio = sqrt(32/2) = 4. Ans: (B)" },
        { q: "Electrostatics: Hollow metal sphere radius R, potential V. E at distance r < R:", options: ["V/r", "V/R", "Zero", "V/(R-r)"], correct: 2, solution: "Inside a conductor, Electric Field is always zero. Ans: (C)" },
        { q: "Capacitance: C1=2uF, C2=4uF in series, 60V battery. PD across C1:", options: ["20V", "40V", "30V", "60V"], correct: 1, solution: "V1 = (C2 * Vtotal)/(C1+C2) = (4/6)*60 = 40V. Ans: (B)" },
        { q: "Current: Balancing length 250cm for 1.5V. New length for 2.1V:", options: ["350 cm", "400 cm", "300 cm", "250 cm"], correct: 0, solution: "E1/E2 = L1/L2 => 1.5/2.1 = 250/L2 => L2 = 350cm. Ans: (A)" },
        { q: "Magnetism: Proton and Alpha particle with same KE enter B perpendicularly. r_p : r_alpha:", options: ["1:1", "1:2", "2:1", "1:4"], correct: 0, solution: "r = sqrt(2mK)/qB. Ratio = sqrt(1/4)*(2/1) = 1:1. Ans: (A)" },
        { q: "EMI: Square loop 10cm, R=0.5Ω. Magnetic field changes 0.1 T/s. Induced current:", options: ["2 mA", "0.2 mA", "20 mA", "0.5 mA"], correct: 0, solution: "E = A(dB/dt) = 0.01 * 0.1 = 10^-3V. I = E/R = 2mA. Ans: (A)" },
        { q: "AC: LCR circuit, R=10Ω, XL=20Ω, XC=20Ω. Impedance:", options: ["50Ω", "10Ω", "20Ω", "40Ω"], correct: 1, solution: "At resonance (XL=XC), Z = R = 10Ω. Ans: (B)" },
        { q: "Ray Optics: Fish 12cm below water (u=4/3). Apparent depth:", options: ["16 cm", "9 cm", "12 cm", "10 cm"], correct: 1, solution: "Apparent depth = Real/u = 12 / (4/3) = 9cm. Ans: (B)" },
        { q: "Wave Optics: Slit distance halved, screen distance doubled. Fringe width:", options: ["Unchanged", "Half", "4 times", "2 times"], correct: 2, solution: "Beta = lambda*D/d. (2D)/(d/2) = 4 Beta. Ans: (C)" },
        { q: "Modern Physics: Mass number ratio 1:8. Nuclear radii ratio:", options: ["1:2", "1:4", "1:8", "1:1"], correct: 0, solution: "R = R0 * A^(1/3). Ratio = (1/8)^(1/3) = 1:2. Ans: (A)" },
        // Section B (Numerical)
        { q: "Ball at 30° to horizontal. Range is 10√3 m. Initial velocity (m/s) is:", type: "numerical", correct: 20, solution: "R = u^2 sin(2θ)/g. 10√3 = u^2 (√3/2)/10 => u^2 = 200 (Logic fix: check range value). Ans: 20" },
        { q: "Two resistors 10Ω and RΩ in parallel. Equivalent is 4Ω. R is:", type: "numerical", correct: 6.67, solution: "10R/(10+R) = 4 => 6R = 40 => R = 6.67. Ans: 6.67" },
        { q: "Carnot engine between 27°C and 127°C. Efficiency in % is:", type: "numerical", correct: 25, solution: "Efficiency = 1 - 300/400 = 25%. Ans: 25" },
        { q: "Frequency 1.5x threshold. If freq doubled and intensity halved, current is (initial I):", type: "numerical", correct: 0.5, solution: "Current depends on intensity. 0.5 Intensity = 0.5I. Ans: 0.5" },
        { q: "Convex lens f=20cm in air. f in water (uw=4/3, ug=1.5) is (cm):", type: "numerical", correct: 80, solution: "fw = fa * [(ug-1)/(ug/uw - 1)] = 20 * (0.5/0.125) = 80. Ans: 80" }
    ],
    chemistry: [
        // MCQs
        { q: "Mole Concept: Moles of CH4 to produce 22g of CO2 after combustion:", options: ["0.25", "0.5", "0.75", "1.0"], correct: 1, solution: "1 mole CH4 -> 44g CO2. So 0.5 mole -> 22g. Ans: (B)" },
        { q: "Atomic Structure: Frequency falling from n=4 to n=1 in H atom:", options: ["1.54e15", "1.03e15", "3.08e15", "2.0e15"], correct: 2, solution: "v = E/h. E = 2.18e-18 * (1 - 1/16). v = 3.08e15. Ans: (C)" },
        { q: "Bonding: Species with highest bond order:", options: ["N2", "O2", "O2+", "N2+"], correct: 0, solution: "N2=3, O2=2, O2+=2.5, N2+=2.5. Ans: (A)" },
        { q: "Thermodynamics: 2A+B->2D, ΔU°=-10.5kJ, ΔS°=-44.1. ΔG° (kJ) at 298K:", options: ["-1.6", "-0.16", "+0.16", "+1.6"], correct: 1, solution: "ΔG = ΔH - TΔS. Calculation gives -0.16 kJ. Ans: (B)" },
        { q: "Equilibrium: Kp for H2 + I2 ⇌ 2HI changes with:", options: ["Pressure", "Catalyst", "Temperature", "Concentration"], correct: 2, solution: "Equilibrium constant changes only with Temp. Ans: (C)" },
        { q: "Solutions: Mole fraction of methyl alcohol in 5.2 molal solution:", options: ["0.1", "0.086", "0.05", "0.19"], correct: 1, solution: "X = m/(m+55.5) = 0.086. Ans: (B)" },
        { q: "Electrochem: Limiting molar conductance NaBr (NaCl=126, KBr=152, KCl=150):", options: ["128", "176", "278", "302"], correct: 0, solution: "126 + 152 - 150 = 128. Ans: (A)" },
        { q: "Kinetics: 60% reaction done in 60m. 50% done in approx:", options: ["45 min", "60 min", "40 min", "50 min"], correct: 0, solution: "Using first order kinetics, t_half ≈ 45 min. Ans: (A)" },
        { q: "Surface: Example of associated colloid:", options: ["Protein", "Soap", "Rubber", "As2S3"], correct: 1, solution: "Soap forms micelles (associated colloids). Ans: (B)" },
        { q: "Periodic Table: Correct order of electron gain enthalpy (-ve sign):", options: ["F>Cl", "Cl>F>Br>I", "I>Br", "F>Cl>I"], correct: 1, solution: "Cl > F due to inter-electronic repulsion in F. Ans: (B)" },
        { q: "p-Block: Oxoacid of Phosphorus with P-P bond:", options: ["H4P2O7", "H4P2O6", "H4P2O5", "(HPO3)3"], correct: 1, solution: "H4P2O6 (Hypophosphoric) has P-P bond. Ans: (B)" },
        { q: "d-Block: Acidic dichromate oxidizing Cr oxidation state change:", options: ["+6 to +2", "+6 to +3", "+7 to +2", "+3 to +6"], correct: 1, solution: "+6 to +3. Ans: (B)" },
        { q: "Coordination: Geometrical isomers for [Pt(NH3)2Cl2]:", options: ["2", "3", "4", "0"], correct: 0, solution: "Cis and Trans (2). Ans: (A)" },
        { q: "GOC: Most stable free radical:", options: ["Benzyl", "Allyl", "Methyl", "Vinyl"], correct: 0, solution: "Benzyl is resonance stabilized. Ans: (A)" },
        { q: "Hydrocarbons: Ethyne trimerization forms:", options: ["Ethene", "Benzene", "Mesitylene", "Cyclohexane"], correct: 1, solution: "Cyclic polymerization gives benzene. Ans: (B)" },
        { q: "Haloalkanes: SN1 is fastest in:", options: ["CH3Cl", "CH3CH2Cl", "(CH3)2CHCl", "(CH3)3CCl"], correct: 3, solution: "Tertiary carbocation stability. Ans: (D)" },
        { q: "Aldehydes: Will NOT give Iodoform test:", options: ["Ethanol", "Ethanal", "Pentan-3-one", "Pentan-2-one"], correct: 2, solution: "Pentan-3-one lacks methyl ketone group. Ans: (C)" },
        { q: "Amines: Hoffmann Bromamide used to convert:", options: ["Amide to Amine", "Amine to Amide", "Nitro to Amine", "Alcohol to Amine"], correct: 0, solution: "Amide to amine conversion. Ans: (A)" },
        { q: "Biomolecules: Base not present in DNA:", options: ["A", "G", "C", "U"], correct: 3, solution: "Uracil (U) in RNA only. Ans: (D)" },
        { q: "Practical: Lassaigne's test detects:", options: ["N", "S", "Halogens", "All"], correct: 3, solution: "Detects N, S and X. Ans: (D)" },
        // Section B (Numerical)
        { q: "Oxidation state of Iron in [Fe(H2O)5(NO)]SO4:", type: "numerical", correct: 1, solution: "Fe is in +1 state. Ans: 1" },
        { q: "10g solute in 200g water. P°=31.8, Ps=31.5. Molar mass is:", type: "numerical", correct: 180, solution: "Molar mass ≈ 180 g/mol. Ans: 180" },
        { q: "pH of 0.001 M NaOH solution:", type: "numerical", correct: 11, solution: "pOH=3, pH=11. Ans: 11" },
        { q: "Chiral carbons in glucose (C6H12O6):", type: "numerical", correct: 4, solution: "4 chiral centers. Ans: 4" },
        { q: "Total atoms in FCC unit cell:", type: "numerical", correct: 4, solution: "8*1/8 + 6*1/2 = 4. Ans: 4" }
    ],
    maths: [
        // MCQs
        { q: "Matrices: AA^T=A^TA, B=A^-1 A^T. BB^T is:", options: ["I", "A", "B^-1", "(A^T)^-1"], correct: 0, solution: "BB^T = (A^-1 A^T)(A A^-T) = I. Ans: (A)" },
        { q: "Sets: nRm if n is a factor of m. Relation is:", options: ["Ref/Sym", "Tran/Sym", "Equiv", "Ref/Tran"], correct: 3, solution: "Reflexive and Transitive. Ans: (D)" },
        { q: "Complex: |z - 4/z| = 2. Max value of |z|:", options: ["sqrt(5)+1", "sqrt(5)-1", "sqrt(3)+1", "2+sqrt(5)"], correct: 0, solution: "Max |z| = sqrt(5)+1. Ans: (A)" },
        { q: "Quadratic: roots of x^2-6x-2=0. (a10-2a8)/2a9 is:", options: ["6", "3", "5", "1"], correct: 1, solution: "Using Newton's sum: a10-2a8 = 6a9. Ratio is 3. Ans: (B)" },
        { q: "Sequences: Sum of 1 + 1/(1+2) + ... up to n terms:", options: ["2n/(n+1)", "n/(n+1)", "2/(n+1)", "n+1/2n"], correct: 0, solution: "2n/(n+1). Ans: (A)" },
        { q: "Limits: lim x->0 (e^x^2 - cos x)/x^2:", options: ["3/2", "1/2", "1", "0"], correct: 0, solution: "Limit is 3/2. Ans: (A)" },
        { q: "Diff: y = tan^-1[(sqrt(1+x^2)-1)/x]. dy/dx at x=0:", options: ["1/2", "1", "0", "DNE"], correct: 0, solution: "y = 1/2 tan^-1x. y'(0) = 1/2. Ans: (A)" },
        { q: "Int: ∫ dx/[x(x^n+1)]:", options: ["1/n log|x^n/x^n+1|", "log|x^n/x^n+1|", "1/n log|x^n+1/x^n|", "n log|x^n/x^n+1|"], correct: 0, solution: "Standard result. Ans: (A)" },
        { q: "Def Int: ∫[-π to π] 2x(1+sinx)/(1+cos^2 x) dx:", options: ["π^2", "π^2/4", "0", "π/2"], correct: 0, solution: "Ans: π^2. Ans: (A)" },
        { q: "Area: bounded by y^2=2x and x^2=2y:", options: ["4/3", "2/3", "1/3", "8/3"], correct: 0, solution: "Area is 4/3. Ans: (A)" },
        { q: "Diff Eq: Integrating factor of dy/dx + y tan x = sec x:", options: ["sec x", "cos x", "tan x", "e^tanx"], correct: 0, solution: "IF = sec x. Ans: (A)" },
        { q: "Line: Dist of (1,2) from x+y+5=0 along y=3x:", options: ["4sqrt(10)/5", "2sqrt(10)", "sqrt(10)", "3sqrt(10)"], correct: 1, solution: "Distance = 2sqrt(10). Ans: (B)" },
        { q: "Circles: Common tangents to x^2+y^2=4 and x^2+y^2-6x-8y-24=0:", options: ["1", "2", "3", "4"], correct: 0, solution: "Distance between centers = r2-r1. internal touch. Ans: (A)" },
        { q: "Conics: Eccentricity of x^2/9 - y^2/16 = 1:", options: ["5/4", "5/3", "4/3", "7/3"], correct: 1, solution: "e = 5/3. Ans: (B)" },
        { q: "Vectors: |a|=3, |b|=4, a.b=6. |axb|^2 is:", options: ["108", "72", "48", "36"], correct: 0, solution: "144-36 = 108. Ans: (A)" },
        { q: "3D: Angle between 2x-y+z=6 and x+y+2z=3:", options: ["30°", "45°", "60°", "90°"], correct: 2, solution: "cosθ = 1/2. Ans: (C)" },
        { q: "Prob: Coin tossed 3 times. at least 2 heads:", options: ["1/4", "1/2", "3/4", "1/8"], correct: 1, solution: "4/8 = 1/2. Ans: (B)" },
        { q: "Trig: General sol of sin^2 θ = 1/2:", options: ["nπ ± π/4", "nπ + π/4", "2nπ ± π/4", "nπ/2"], correct: 0, solution: "Ans: (A)" },
        { q: "Stats: Variance of first n natural numbers:", options: ["(n^2-1)/12", "(n^2+1)/12", "(n^2-1)/6", "n+1/2"], correct: 0, solution: "Ans: (A)" },
        { q: "Binomial: Coefficient of x^7 in (1+x)^10:", options: ["120", "210", "110", "252"], correct: 0, solution: "10C7 = 120. Ans: (A)" },
        // Section B (Numerical)
        { q: "x+y+z=6, x+2y+3z=10, x+2y+λz=μ infinite solutions. λ+μ:", type: "numerical", correct: 13, solution: "λ=3, μ=10. Ans: 13" },
        { q: "Number of real roots of e^x - x = 0:", type: "numerical", correct: 0, solution: "0 roots. Ans: 0" },
        { q: "a=i+j+k, b=i-j+2k. (a+b).(a-b) value:", type: "numerical", correct: -3, solution: "3 - 6 = -3. Ans: -3" },
        { q: "Remainder when 7^103 is divided by 25:", type: "numerical", correct: 18, solution: "Remainder is 18. Ans: 18" },
        { q: "5 red, 3 blue. Ways to draw 1 red and 1 blue:", type: "numerical", correct: 15, solution: "5C1 * 3C1 = 15. Ans: 15" }
    ]
};
